CREATE DATABASE IF NOT EXISTS OFICINA_SAEP_DB;
USE OFICINA_SAEP_DB;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_ID INT AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(100) NOT NULL,
    USU_EMAIL VARCHAR(100) NOT NULL,
    USU_SENHA VARCHAR(100) NOT NULL
);

CREATE TABLE CLIENTES (
    CLI_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLI_NOME VARCHAR(100) NOT NULL,
    CLI_CPF VARCHAR(14) NOT NULL UNIQUE,
    CLI_TELEFONE VARCHAR(20) NOT NULL
);

CREATE TABLE VEICULOS (
    VEI_ID INT AUTO_INCREMENT PRIMARY KEY,
    VEI_PLACA VARCHAR(10) NOT NULL UNIQUE,
    VEI_MARCA VARCHAR(50) NOT NULL,
    VEI_MODELO VARCHAR(100) NOT NULL,
    FK_CLI_ID INT NOT NULL,
    FOREIGN KEY (FK_CLI_ID) REFERENCES CLIENTES(CLI_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE AGENDAMENTOS (
    AGE_ID INT AUTO_INCREMENT PRIMARY KEY,
    AGE_DATA_HORA DATETIME NOT NULL,
    AGE_SERVICO VARCHAR(150) NOT NULL,
    AGE_STATUS VARCHAR(30) NOT NULL,
    FK_CLI_ID INT NOT NULL,
    FK_VEI_ID INT NOT NULL,
    FOREIGN KEY (FK_CLI_ID) REFERENCES CLIENTES(CLI_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (FK_VEI_ID) REFERENCES VEICULOS(VEI_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO USUARIO(USU_NOME, USU_EMAIL, USU_SENHA)
VALUES 	("Admin", "admin@admin.com", "admin123"),
		("Paula", "paula@email.com", "123456"),
        ("Gabriel", "gabriel@email.com", "123456");
        
INSERT INTO CLIENTES(CLI_NOME, CLI_CPF, CLI_TELEFONE)
VALUES 	("Gabriel", "22309875660", "19887654323"), -- CLI_ID - 1
		("Luiz", "33465782134","19223450987"), -- CLI_ID - 2
        ("Leonardo", "44020904820","19993173392"); -- CLI_ID - 3
        
INSERT INTO VEICULOS(VEI_PLACA , VEI_MARCA , VEI_MODELO, FK_CLI_ID )
VALUES  ("ABC1D23", "Toyota", "Corolla", 2), -- CLI_ID - 1
		("DEF4E56", "Chevrolet","Onix", 1), -- CLI_ID - 2
        ("GHI7F89", "Volkswagen","Gol", 3); -- CLI_ID - 3
        
INSERT INTO AGENDAMENTOS(AGE_DATA_HORA, AGE_SERVICO, AGE_STATUS, FK_VEI_ID, FK_CLI_ID)
VALUES 	("2026-09-29 08:00:00", "troca de oleo", "Agendada", 1, 2),
		("2026-09-29 08:30:00", "Pneu furado", "Agendada", 2, 1),
        ("2026-09-29 09:00:00", "vazamento de agua", "Agendada", 3, 3);
        
